### ISSUE TITLE
Policy Table Update Fails to find sdl_snapshot.json when using a Cloud App

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/manticore#120] opened 2020-10-02 13:49 UTC
When testing Policy table Updates with a JavaSE application the Policy Table Update fails to send a populated body in the OnSystemRequest RPCmessage. Reviewing the logs in manticore the issues seems to be a result of a missing file (sdl_snapshot.json).

Manticore Logs:
`20769 DEBUG [18:30:51,812][Utils::FileSystem] Filename: /tmp/fs/mp/images/ivsu_cache/sdl_snapshot.json
 20770 ERROR [18:30:51,812][Utils::FileSystem] Unable to check that file exists: /tmp/fs/mp/images/ivsu_cache/sdl_snapshot.json reason: No such file or directory, error code 2 (No such file or directory)
 20771 ERROR [18:30:51,812][Utils::FileSystem] Not able to read binary file: /tmp/fs/mp/images/ivsu_cache/sdl_snapshot.json`

Reproduction Steps:
1) Add Hello Sdl Java as a web app in manticore
2) Start the Hello Sdl Java app and connect to manticore
3) Update the Policy Table URL

Expected Behavior:
An OnSystemRequest RPCmessage is sent to the app with a populated body

Observed Behavior:
An OnSystemRequest RPCmessage is sent to the app with an empty String for a body

**Comment by renonick87** [comment] 2021-09-22 20:45
Closed as duplicate of #140 which has been resolved.

**Closed by renonick87** 2021-09-22 20:45 UTC
Labels: bug
