### ISSUE TITLE
SetInteriorVehicleData RPC sometimes is REJECTED on developer portal Manticore

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/manticore#98] opened 2019-12-05 17:03 UTC
Symptoms found while testing:

The rate of failure seems to rely only on startup between manticore and core. so, there's a small chance (~20%) that when an instance is received, it will REJECT when an app connects and sends a setinterior. the failure rate doesn't seem to depend on what or how many setinteriors the app sends.

error messages: "User location is not valid", "Resource acquisition is not allowed according to location verification."

Im only able to reproduce the issue, and I was using the java suite app. I asked someone else to try and reproduce it and the error didn't happen.

the error happens when Im not sending in any specific module id. not sure whether sending a specific module id would cause the error to happen also

disconnecting the app and reconnecting the app will cause the setinterior RPCs to succeed
when it does succeed, it will not fail again (unless I got lucky)

I tried removing the seat capabilities in the RC capabilities response from the manticore UI and so far I haven't gotten any errors regarding setting RC data

being reasonably sure about a behavior meant attempting the process up to 14 times (using 95% certainty and assumed a 20% failure rate)

when the error does show up:
	it will continue to error on successive setinteriors until the app disconnects and reconnects, then tries again
	the RC resource is free
	RC button presses dont work either. RC button presses via the UI will still work, but sending a ButtonPress RPC through the app results in REJECTED
	for button presses being REJECTED, the same reason for failure happens as sending SetInteriors

**Comment by renonick87** [comment] 2021-04-28 15:53
Closing this issue as we have been unable to reproduce it since it has been reported.

**Closed by renonick87** 2021-04-28 15:53 UTC
